
const CONSTANTS = {
  REGISTRO: 'REGISTRO',
  LOGIN: 'LOGIN',
  LOGIN_PHONE: "LOGIN_PHONE",
  ESTABLERCER_SESION: 'ESTABLERCER_SESION',
  CERRAR_SESION: 'CERRAR_SESION'
};

export default CONSTANTS;
