# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'AtyClientRN' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AtyClientRN
  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging', '~> 5.15.0'
  pod 'Firebase/Database'
  pod 'GoogleMaps'
# facebook
  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'CxxBridge',
  'DevSupport',
  'RCTActionSheet',
  'RCTAnimation',
  'RCTGeolocation',
  'RCTImage',
  'RCTLinkingIOS',
  'RCTNetwork',
  'RCTSettings',
  'RCTText',
  'RCTVibration',
  'RCTWebSocket',
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  
  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # react-native-maps dependencies
  pod 'react-native-maps', path: rn_maps_path
  
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

end
# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     if target.name == 'react-native-google-maps'
#       target.build_configurations.each do |config|
#         config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
#       end
#     end
#     if target.name == "React"
#       target.remove_from_project
#     end
#   end
# end